// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk6tw0jfgUzfMA0xJHqKzDWU7MWyHF7Zc',
    appId: '1:1064411966305:web:5d1ce7688d88112704b320',
    messagingSenderId: '1064411966305',
    projectId: 'awesome-89e82',
    authDomain: 'awesome-89e82.firebaseapp.com',
    storageBucket: 'awesome-89e82.firebasestorage.app',
    measurementId: 'G-5K6LXRDRRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAphkXBLbeRXdW86m8AuSqNIURA_qk8Xmo',
    appId: '1:1064411966305:android:c46cd9a2abc7914204b320',
    messagingSenderId: '1064411966305',
    projectId: 'awesome-89e82',
    storageBucket: 'awesome-89e82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVOEvggcUXS182sU4zKVHmFqcwmyjXkVM',
    appId: '1:1064411966305:ios:315c76e363fc47ba04b320',
    messagingSenderId: '1064411966305',
    projectId: 'awesome-89e82',
    storageBucket: 'awesome-89e82.firebasestorage.app',
    androidClientId: '1064411966305-1d7dfpd98b9169cd1pa1pqjsmcsk4ckk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gsadrive',
  );
}
